# Generated by Django 4.2.23 on 2025-06-28 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("index", "0009_ensure_song_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(default=0.0, verbose_name="相似度分数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "song1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_song1",
                        to="index.song",
                        verbose_name="歌曲1",
                    ),
                ),
                (
                    "song2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_song2",
                        to="index.song",
                        verbose_name="歌曲2",
                    ),
                ),
            ],
            options={
                "verbose_name": "物品相似度",
                "verbose_name_plural": "物品相似度",
                "unique_together": {("song1", "song2")},
            },
        ),
    ]
