# Generated by Django 4.2.23 on 2025-06-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist1", models.CharField(max_length=100, verbose_name="歌手1")),
                ("artist2", models.CharField(max_length=100, verbose_name="歌手2")),
                (
                    "similarity_score",
                    models.FloatField(default=0.0, verbose_name="相似度分数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "歌手相似度",
                "verbose_name_plural": "歌手相似度",
                "unique_together": {("artist1", "artist2")},
            },
        ),
    ]
