# Generated by Django 5.2.1 on 2025-06-26 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aiassistant", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="ChatSession",
        ),
    ]
