# Generated by Django 3.2.11 on 2025-06-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiassistant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
