# Generated by Django 3.2.11 on 2025-06-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiassistant', '0002_auto_20250626_1512'),
        ('aiassistant', '0002_delete_chatmessage_delete_chatsession'),
    ]

    operations = [
    ]
