# Generated by Django 5.2.1 on 2025-06-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0002_auto_20220614_1733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="song_file",
            field=models.FileField(max_length=50, upload_to="", verbose_name="歌曲文件"),
        ),
        migrations.AlterField(
            model_name="song",
            name="song_img",
            field=models.FileField(max_length=20, upload_to="", verbose_name="歌曲图片"),
        ),
        migrations.AlterField(
            model_name="song",
            name="song_lyrics",
            field=models.FileField(
                default="暂无歌词", max_length=50, upload_to="", verbose_name="歌词"
            ),
        ),
    ]
