# Generated by Django 3.2.11 on 2025-06-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_song_song_file_alter_song_song_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_album',
            field=models.CharField(max_length=200, verbose_name='专辑'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_name',
            field=models.CharField(max_length=200, verbose_name='歌名'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_singer',
            field=models.CharField(max_length=100, verbose_name='歌手'),
        ),
    ]
