# Generated by Django 3.2.11 on 2025-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20250622_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(max_length=255, upload_to='', verbose_name='歌曲文件'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_img',
            field=models.FileField(max_length=255, upload_to='', verbose_name='歌曲图片'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_lyrics',
            field=models.FileField(default='暂无歌词', max_length=255, upload_to='', verbose_name='歌词'),
        ),
    ]
