# Generated by Django 3.2.11 on 2025-06-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20250622_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_img_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='图片链接'),
        ),
    ]
