# Generated by Django 3.2.11 on 2025-06-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_song_song_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics_text',
            field=models.TextField(blank=True, null=True, verbose_name='歌词内容'),
        ),
    ]
