# Generated by Django 5.1.2 on 2025-06-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_song_lyrics_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mv_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='MV链接'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_mv',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='songMV', verbose_name='MV文件'),
        ),
    ]
