# Generated by Django 4.2.23 on 2025-06-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0009_ensure_song_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="emotion_label",
            field=models.CharField(
                blank=True,
                choices=[("happy", "开心"), ("sad", "伤感"), ("neutral", "中性")],
                help_text="歌词情感标签",
                max_length=20,
                null=True,
            ),
        ),
    ]
