# Generated by Django 5.2.1 on 2025-07-01 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0009_song_mv_url_song_song_mv"),
        ("index", "0010_song_emotion_label"),
    ]

    operations = []
