# Generated by Django 5.2.1 on 2025-07-01 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0011_merge_20250701_1445"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="mv_url",
        ),
        migrations.RemoveField(
            model_name="song",
            name="song_mv",
        ),
    ]
