# Generated by Django 5.2.1 on 2025-06-25 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0008_song_lyrics_text"),
        ("user", "0003_alter_myuser_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SongLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listen_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="听歌时间"),
                ),
                (
                    "listen_count",
                    models.PositiveIntegerField(default=1, verbose_name="听过的次数"),
                ),
                (
                    "total_listen_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="总听歌时长(秒)"),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="index.song",
                        verbose_name="歌曲",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "听歌记录",
                "verbose_name_plural": "听歌记录",
            },
        ),
    ]
