# Generated by Django 5.2.1 on 2025-06-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_songlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="nickname",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="昵称"
            ),
        ),
    ]
