# Generated by Django 5.2.1 on 2025-06-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_myuser_bio_alter_myuser_qq_alter_myuser_wechat"),
    ]

    operations = [
        migrations.AddField(
            model_name="songlog",
            name="song_languages",
            field=models.CharField(default="中文", max_length=20, verbose_name="语种"),
        ),
        migrations.AddField(
            model_name="songlog",
            name="song_type",
            field=models.CharField(default="中文", max_length=20, verbose_name="类型"),
            preserve_default=False,
        ),
    ]
