# Generated by Django 3.2.11 on 2025-06-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_songlog_song_languages_songlog_song_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlog',
            name='song_languages',
            field=models.CharField(blank=True, default='中文', max_length=20, null=True, verbose_name='语种'),
        ),
        migrations.AlterField(
            model_name='songlog',
            name='song_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='类型'),
        ),
    ]
