# Generated by Django 3.2.11 on 2025-06-26 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0008_song_lyrics_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='场景名称')),
            ],
            options={
                'verbose_name': '使用场景',
                'verbose_name_plural': '使用场景',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '歌曲标签',
                'verbose_name_plural': '歌曲标签',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('comment_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='内容')),
                ('comment_user', models.CharField(max_length=20, verbose_name='用户')),
                ('comment_date', models.CharField(max_length=50, verbose_name='日期')),
                ('rating', models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], null=True, verbose_name='评分')),
                ('emotion', models.CharField(choices=[('happy', '开心'), ('sad', '伤感'), ('excited', '兴奋'), ('relaxed', '放松'), ('nostalgic', '怀旧'), ('other', '其他')], max_length=20, null=True, verbose_name='情感')),
                ('scenes', models.ManyToManyField(blank=True, to='comment.Scene', verbose_name='适合场景')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_comments', to='index.song', verbose_name='歌名')),
                ('tags', models.ManyToManyField(blank=True, to='comment.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '歌曲点评',
                'verbose_name_plural': '歌曲点评',
            },
        ),
    ]
